In [9]:
import numpy as np

In [10]:
np.random.seed(1)

In [11]:
x=np.random.randn(2,3)

In [12]:
x

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [13]:
y=np.array([[1,0,1]])

In [14]:
y

array([[1, 0, 1]])

In [15]:
def layer_size(x,y):
    n_x=x.shape[0]
    n_h=4
    n_y=y.shape[0]
    return(n_x,n_h,n_y)

In [16]:
layer_size(x,y)

(2, 4, 1)

In [18]:
def int_value(n_x,n_h,n_y):
    np.random.seed(2)
    w1=np.random.randn(n_h,n_x)*0.01
    b1=np.zeros(shape=(n_h,1))
    w2=np.random.rand(n_y,n_h)*0.01
    b2=np.zeros(shape=(n_y,1))
    parameters = {"w1":w1,"b1":b1,"w2":w2,"b2":b2}
    
    return parameters

In [21]:
n_x,n_h,n_y=2, 4, 1
parameters=int_value(n_x,n_h,n_y)

In [22]:
parameters

{'w1': array([[-0.00416758, -0.00056267],
        [-0.02136196,  0.01640271],
        [-0.01793436, -0.00841747],
        [ 0.00502881, -0.01245288]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'w2': array([[0.00299655, 0.00266827, 0.00621134, 0.00529142]]),
 'b2': array([[0.]])}

In [23]:
def sigmoid(z):
    s=1/(1+np.exp(-z))
    return s

In [24]:
## Step 1 - Forward PRG

def fwd_prg(x,parameters):
    w1=parameters['w1']
    b1=parameters['b1']
    w2=parameters['w2']
    b2=parameters['b2']
    
    z1=np.dot(w1,x)+b1
    a1=np.tanh(z1)
    z2=np.dot(w2,a1)+b2
    a2=sigmoid(z2)
    
    catch={"z1":z1,"a1":a1,"z2":z2,"a2":a2}
    
    return a2, catch

In [25]:
a2, catch= fwd_prg(x,parameters)

In [26]:
a2

array([[0.4999578 , 0.50000713, 0.50006414]])

In [27]:
catch

{'z1': array([[-0.00616586,  0.00206261,  0.0034962 ],
        [-0.05229879,  0.02726335, -0.02646868],
        [-0.0200999 ,  0.00368691,  0.02884556],
        [ 0.02153008, -0.01385323,  0.02600471]]),
 'a1': array([[-0.00616578,  0.0020626 ,  0.00349619],
        [-0.05225116,  0.02725659, -0.0264625 ],
        [-0.0200972 ,  0.00368689,  0.02883756],
        [ 0.02152676, -0.01385234,  0.02599885]]),
 'z2': array([[-1.68819775e-04,  2.85106887e-05,  2.56558028e-04]]),
 'a2': array([[0.4999578 , 0.50000713, 0.50006414]])}

In [28]:
def compute_cost(a2,y,parameters):
    m=y.size
    cost=-np.sum(y*np.log(a2)+(1-y)*np.log(1-a2))/m
    return cost

In [29]:
cost=compute_cost(a2,y,parameters)

In [30]:
cost

0.6931373132632764